### ISSUE TITLE
Privacy properties of zDai

### ISSUE THREAD

**Issue by john-light** [snjax/zDai-mixer#2]
Very cool project!

"Confidential Transactions" is a well-known technique for encrypting _transaction amounts_, however there is a weakness with the tech which is that it leaves the transaction graph (the sender and recipient) transparent/ public.

Does zDai work like Confidential Transactions where it only encrypts the transaction amount? Or does zDai also encrypt the transaction graph to hide the sender and recipient from the public?

**Comment by poma** [comment]
zDai encrypts both amounts and addresses. The smart contract stores only hashes of UTXOs

**Comment by john-light** [comment]
@poma thanks! You may want to use a different term than "confidential transactions" e.g. "confidential private transaction", "confidential Dai transactions" in the documentation to prevent confusion with the well-known [Confidential Transactions](http://diyhpl.us/wiki/transcripts/gmaxwell-confidential-transactions/) technique.

**Comment by poma** [comment]
Done
